name: sneaker_shopping_prokit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  nb_utils: ^7.1.4
  intl: ^0.20.2
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - images/sneakerShopping/
